language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
before_install: npm install -g grunt-cli
script: npm test
after_success: script/gh-pages.sh
env:
  global:
    secure: ZhWDhSIFkxZef81qDGVOR9x6XCrNndMSrZtWq+ZkaZj+qDnzfGSgSZ0Q3p7iFcs8Or7oVEDzihdfWb3Sb+4ppopBbkEFjHKCksRKTvJd3mHVxwiMOJ64yd6WfJsCsJOYK0CWQZRvG7baGg2gcPP3OSnLzxERp/nNYiYM3K6CkmAiEJsoxacB86hQxSf9VRDW95nuj5xWA5Y4tNsCvvLnBlQrex9NHVppsJ0dhNzSNPZnuPG6yQgq4ZvAz5msgrQkMtzVyfD2VDLzhKk6m5+vQ5qu9ciqJdpbyltGW9zvFFEMQhoOTQoiCPX4xStYnRWhi47XrA1qLPOhzxtiBTq+9OJiYc3TPALLnQuuHdCDNsi2WGglyybqOMMqcuO2jpFHcuTPFN9OuQtR2Xbhquq7YYarlGOX6EVhL6KM/ABKwJJl3HTCmdPyCgPKuzaKDuChK0xddDCC0atmOvI4o2++lPjM3eLz+0qbFTrx2qSLHDacjSlYXI39kha4BuxO8iUlzXu4GjLUelUHhn6IdE44/BFfLV+ITQ0bNC/68Oj0yzTnXFyDq51gcpdhQLWnPePZ0BO/cKpZAiBLDZQSAmazqiJCO9Tekiwb3bF59locwpB9yzz7NOi6QMZ5U5MrQbWSHjQbmA1s9qW9PeDWnCq9juLsCs3xUjh4XGijV5FUuYE=
